FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app


# Dependências necessárias para mysqlclient
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    pkg-config \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*


# Instala dependências Python
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


# Copia TODO o backend
COPY . .


# Usuário não-root
RUN useradd -m appuser \
    && chown -R appuser:appuser /app

USER appuser


EXPOSE 5000


CMD [ "gunicorn", "--workers", "1", "--threads", "100", "--bind", "0.0.0.0:5000", "--access-logfile", "-", "--error-logfile", "-", "api:app" ]